[package]
name = "elasticsearch_rust_example"
version = "0.1.0"
authors = ["Russ Cam"]
edition = "2018"

[dependencies]
elasticsearch = "7.6.0-alpha.1"
serde = "~1"
serde_json = "~1"
tokio = { version = "0.2.8", features = ["full"] }